services:
  auth210-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth210-api
    working_dir: /app
    ports:
      - "3001:3001"
      - "9229:9229"  # debugger port
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16-alpine
    container_name: auth210-db
    environment:
      POSTGRES_DB: auth210
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: auth210-redis
    # ports:
    #   - "6379:6379"
volumes:
  pgdata:
